In [1]:
import pandas as pd
import numpy as np
import regex as re
import locationtagger
from deep_translator import GoogleTranslator

In [2]:
product_details = pd.read_csv('product_details.csv')
product_base = pd.read_csv('product_base.csv')

/var/folders/3c/dwwhhxpn5v1_gqzr69zmy0900000gn/T/ipykernel_6748/2588855562.py:1: DtypeWarning: Columns (25,27,28,29,30,31,32,33,34,42,46,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,64,65,66,67,68,69,71,72,74,75,77,79,80,83,84,85,86,87,88,89,90,91,92,93,94,97,99,100,101,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,214,215,216,217,218,219,220,221,222,223,224,225,226,227,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,613,614,615,617,618,620,621,622,623,624,625,626,627,629,630,631,632,633,634,635,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653) have mixed types. Specify dtype option on import or set low_memory=False.
  product_details = pd.read_csv('product_details.csv')

In [3]:
product_base.head()

,Unnamed: 0,Referencja,EAN,Nazwa,Dane Produktowe
0,0,97,5010338303006,Blue Dragon - PraÅ¼one algi morskie do sushi n...,https://apps.auchan.pl/feed/getCard/97
1,1,143,5010338303273,Blue Dragon - RyÅ¼ do sushi - 500 g,https://apps.auchan.pl/feed/getCard/143
2,2,1864,5941866617474,Verdino - RoÅlinne plastry pepperoni - 80 g,https://apps.auchan.pl/feed/getCard/1864
3,3,7441,5902506003187,Kolorado - Kostka wc barwiÄ ca do spÅuczki - ...,https://apps.auchan.pl/feed/getCard/7441
4,4,8499,5900143008107,Taverna Dell Ancora - Tortellini z miÄsem - 2...,https://apps.auchan.pl/feed/getCard/8499

In [4]:
product_base = product_base.drop(columns=['Unnamed: 0'])
product_base['EAN'] = product_base['EAN'].apply(str)
product_base['Referencja'] = product_base['Referencja'].apply(str)

In [5]:
product_details.shape

(10261, 654)

In [6]:
product_details.columns.tolist()

['Unnamed: 0',
 'Referencja',
 'waga',
 'zalecenia dla alergikow',
 'opis produktu',
 'marka standaryzowana',
 'informacje dot stylu zycia',
 'jednostka opisowa',
 'kraj pochodzenia',
 'marka',
 'wartość energetyczna',
 'tłuszcz',
 'tym kwasy tłuszczowe nasycone',
 'węglowodany',
 'tym cukry',
 'białko',
 'sól',
 'przygotowanie',
 'błonnik',
 'uzytkowanie i przechowywanie',
 'nazwa produktu ureg prawnie',
 'podmarka',
 'dodatkowe informacje',
 'cechy',
 'dodatki',
 'wartość energetyczna kcal',
 'tłuszcz tym',
 'kwasy nasycone',
 'kwasy jednonienasycone',
 'kwasy wielonienasycone',
 'inne',
 'kwas alfa linolenowy omega',
 'sód',
 'zawartość soli wynika wyłącznie obecności naturalnie występującego sodu',
 'białka',
 'warunki przechowywania',
 'pole rezerwowe 20',
 'pochodzenie',
 'energia',
 'tym kwasy nasycone',
 'witamina',
 'rozszerzona nazwa produktu',
 'rws referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal',
 'Unnamed: 43',
 'kwasy tłuszczowe nasycone',
 'cukry',
 'wartość energetyczna energia kcal',
 'referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal',
 'kationy',
 'magnezowy',
 'wapniowy',
 'sodowy',
 'potasowy',
 'aniony',
 'wodorowęglanowy hco',
 'siarczanowy',
 'chlorkowy',
 'fluorkowy',
 'ogólna zawartość rozpuszczonych składników mineralnych',
 'składniki mineralne niezdysocjowane',
 'kwas metakrzemowy sio',
 'suma składników stałych',
 'dostawa wersji zależy regionu',
 'wapń',
 'zawartość laktozy',
 'kubek zawiera porcję równą',
 'bcaa',
 'opakowanie zawiera sugerowaną porcję produktu',
 'bcaa aminokwasy egzogenne rozgałęzione walina izoleucyna leucyna',
 'dzienna referencyjna wartość spożycia wapnia dla osoby dorosłej',
 'opakowanie zawiera porcji',
 'zawartość tłuszczu',
 'materia nieorganiczna',
 'włókno surowe',
 'wilgotność',
 'smaki',
 'dodatki dietetyczne',
 'tauryna',
 'miedź pięciowodny siarczan miedzi',
 'jod jodan wapnia bezwodny',
 'żelazo siarczan żelaza jednowodny',
 'mangan siarczan manganawy jednowodny',
 'cynk siarczan cynku jednowodny',
 'dodatki technologiczne',
 'guma kasja',
 'opakowanie pozwala przygotowanie porcji',
 'referencyjnej wartości spożycia dla przeciętnej osoby dorosłej kcal',
 'kwasy tłuszczowe jednonienasycone',
 'kwasy tłuszczowe wielonienasycone',
 'rodzaj alkoholu',
 'miejsce uboju',
 'rozmiar porcji',
 'ilość porcji opakowaniu',
 'wit',
 'aromaty',
 'tłuszcz surowy',
 'popiół surowy',
 'włókno rozpuszczalne',
 'kwasy tłuszczowe omega',
 'ryboflawina',
 'kwas foliowy',
 'drws dzienne referencyjne wartości spożycia witamin składników mineralnych dla osób dorosłych',
 'węglowodany tym',
 'opakowanie zawiera porcji wielkość porcji powinna być dostosowana wieku dziecka',
 'wielkość porcji powinna być dostosowana wieku dziecka',
 'opakowanie zawiera porcje',
 'tym nasycone kwasy tłuszczowe',
 'logotypy stron trzecich cd',
 'opakowanie zawiera porcji produktu',
 'opakowanie zawiera około porcje jedna porcja mała garść produktu',
 'referencyjna wartość spożycia',
 'cukry ogółem',
 'równoważna zawartość soli',
 'ilość porcji opakowania',
 'tłuszcze',
 'tuszcz',
 'składnik',
 'cynk',
 'miedź pantahydrat siarczanu miedzi',
 'żelazo siarczan żelaza monohydrat',
 'mangan siarczan manganawy monohydrat',
 'cynk siarczan cynku monohydrat',
 'azotyn sodu',
 'niacyna',
 'kwas pantotenowy',
 'opakowanie zawiera sugerowane porcje produktu',
 'opakowanie zawiera porcję produktu',
 'przeciwutleniacze konserwanty barwniki',
 'tłuszcze nasycone',
 'cukier',
 'jednonienasycone',
 'wielonienasycone',
 'omega kwas alfa linolenowy',
 'stanole roślinne',
 'opakowanie zawiera butelek butelka zawiera porcję równą',
 'alkohole wielowodorotlenowe poliole',
 'tym kwasy tłuszczowe jednonienasycone',
 'tym kwasy tłuszczowe wielonienasycone',
 'witaminy składniki mineralne',
 'magnez',
 'fosfor',
 'dzienne referencyjne wartości spożycia witamin składników mineralnych dla osoby dorosłej',
 'opakowanie zawiera około porcji produktu porcja',
 'potas',
 'butelka zawiera porcję równą',
 'przeciwutleniacze barwniki',
 'żelazo',
 'rws referencyjna wartość spożycia',
 'jod jodek potasu',
 'butelka zawiera porcji',
 'zawiera znikome ilości tłuszczu tym kwasów nasyconych białka soli',
 'wymiennik węglowodanowy',
 'informacja dla diabetyków porcja kromka',
 'witaminy',
 'tiamina',
 'informacja dla osób chorych cukrzycę zawartość wymienników produktu wbt',
 'nasycone tym kwasy tłuszczowe',
 'fenyloalanina',
 'opakowanie zawiera sugerowaną porcję',
 'tiamina witamina',
 'zalecanego dziennego spożycia',
 'informacja dla diabetyków produktu zawiera wbt',
 'referencyjnej wartości spożycia',
 'laktoza',
 'przeciwutleniacze konserwanty',
 'dodatki sensoryczne',
 'smak wołowiny',
 'smak jagnięciny',
 'smak drobiu',
 'informacje dot stylu zycia cd',
 'tym fenyloalanina',
 'opakowanie zawiera jedną sugerowaną porcję',
 'wartosc energetyczna',
 'tym nasycone',
 'około gotowego ciasta porcji',
 'siarczan żelaza monohydrat',
 'bezwodny jodan wapnia',
 'pentahydrat siarczanu miedzi',
 'siarczan manganawy monohydrat',
 'jednowodny siarczan cynku',
 'opakowanie zawiera butelki butelka zawiera porcję równą',
 'biotyna',
 'miedź pięciowodny siarczanu miedzi',
 'dostosuj wielkość porcji swoich potrzeb',
 'opakowanie zawiera porcji gramowych',
 'referencyjnej wartości spożycia dla dorosłych rozporządzenia',
 'nrv referencyjne wartości spożycia',
 'składniki mineralne',
 'dzienna referencyjna wartość spożycia witamin składników mineralnych dla osób dorosłych',
 'energis',
 'opakowanie zawiera porcję',
 'wartosc energetyczna kcal',
 'bialko',
 'weglowodany',
 'tluszcz',
 'tym kwasy tluszczowe nasycone',
 'sol',
 'referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal dla gramów zamrożonego produktu przygotowanego piekarniku zgodnie wytycznymi gotowania',
 'porcja opakowanie wystarcza przygotowania porcji zupy',
 'opakowanie zawiera plasterków',
 'dziennej referencyjnej wartości spożycia dla przeciętnej osoby dorosłej',
 'opakowanie zawiera sugerowane porcje',
 'konserwanty',
 'mangan',
 'miedź',
 'jod',
 'selen',
 'ekstrakt tokoferoli olejów roślinnych',
 'ekstrakt rozmarynu',
 'białko surowe',
 'wtym kwasy tłuszczowe nasycone',
 'wtym cukry',
 'opakowanie zawiera sugerowanych porcji produktu',
 'przeciwutleniacze',
 'barwniki',
 'selen selenin sodu',
 'pierwiastki śladowe',
 'siarczan miedzi pięciowodny miedź',
 'jodek potasu jod',
 'siarczan żelazawy jednowodny żelazo',
 'siarczan manganawy jednowodny mangan',
 'tlenek cynku cynk',
 'selenin sodu selen',
 'zds zalecane dzienne spożycie',
 'wartość enegetyczna',
 'tiamina wit',
 'kwas linolenowy ala',
 'porcja kaszki wody',
 'witaminy grupy',
 'barwniki przeciwutleniacze',
 'kwasy tłuszczowe omega kwas linolowy',
 'kwas tłuszczowy omega kwas linolenowy',
 'blonnik',
 'tym kwas alfa linolenowy ala',
 'tym kwas eikozapentaenowy epa',
 'tym kwas dokozaheksaenowy dha',
 'wartość energetyczna energia',
 'zawiera naturalnie występujące cukry',
 'opakowanie stanowi jedną porcję',
 'opakowanie zawiera około porcji pełnowartościowych posiłków mleczno zbożowych',
 'jednowodny siarczan magnezu',
 'selenin sodu',
 'porcja lód',
 'dzienna referencyjna wartość spożycia witaminy wynosi',
 'procent referencyjnego dziennego spożycia witaminy',
 'niacyna wit',
 'produkt zawiera porcji',
 'opakowanie zawiera porcji pełnowartościowego posiłku zbożowo mlecznego',
 'produkt zawiera porcji wafelek',
 'porcja woreczka suchego produktu produktu ugotowaniu wodzie bez soli',
 'opakowanie zawiera porcji ryżu',
 'wartość średnia uwzględniająca sezonową zmienność owoców',
 'zawartość polifenoli produktu',
 'baton stanowi porcję',
 'omega ala',
 'ala kwas alfa linolenowy',
 'porcja opakowanie zawiera około porcje',
 'region pochodzenia',
 'porcja opakowanie pozwala przygotowanie porcji sosu',
 'przyrządzeniu mlekiem zawartości tłuszczu',
 'siarczan zelaza monohydrat',
 'oleje tłuszcze surowe',
 'tym kwasy tłuszczowe nasycone kwasy nasycone',
 'produkt zawiera porcję',
 'opakowanie zawiera około porcji',
 'opakowanie zawiera porcji łyżka',
 'rws referencyjna wartość spożyją dla przeciętnej osoby dorosłej kcal',
 'kwas dokozaheksaenowy dha',
 'porcja dania opakowanie wystarcza przygotowania porcji',
 'nutri score obliczono dla produktu',
 'kcal',
 'deser można podzielić porcje porcja około',
 'omega kwas linolowy',
 'omega kwas oleinowy',
 'referencyjna wartość spożycia dla przeciętnej osoby',
 'zalecana wartość spożycia dla przeciętnej osoby dorosłej kcal',
 'opakowanie zawiera butelki',
 'porcje',
 'opakowanie zawiera porcje produktu',
 'przyrządzeniu kostką litr',
 'tym alkohole poliole',
 'karnityna',
 'produkt zawiera porcji paluszek',
 'tym tłuszcze nasycone',
 'jednowodny siarczan manganu',
 'składniki analityczne',
 'tym',
 'chlorek',
 'gos fos',
 'fukozylolaktoza',
 'galaktozylolaktoza',
 'opakowanie bebilon profutura pozwala przygotowanie około kubków mleka zgodnie tabelą żywienia',
 'galaktooligosacharydy fruktooligosacharydy',
 'zawartość kwasów tłuszczowych omega epa dha',
 'zawartość witaminy',
 'suma kwasów omega',
 'epa',
 'dha',
 'omega',
 'energia kcal',
 'cukru',
 'smak kocimiętki',
 'zawartość soli wynika wyłącznie naturalnie występującego sodu',
 'referencyjnych wartości spożycia dla przeciętnej osoby dorosłej kcal',
 'produkt zawiera porcji kostki',
 'inki około porcji',
 'zawartość soli wynika wyłącznie naturalnej zawartości sodu',
 'wodorowęglany',
 'osmolalność mosm',
 'witamina octan alfa tokoferylu',
 'miedź siarczan miedzi pięciowodny',
 'jod jodan wapnia',
 'opakowanie zawiera porcji produktu kromek',
 'fluorki',
 'witaminy minerały',
 'dziennej referencyjnej wartości spożycia dla osoby dorosłej',
 'porcja porcji',
 'przygotowany budyń można podzielić porcje porcja około',
 'porcja około',
 'przygotowany budyń można podzielić porcje',
 'porcja',
 'sernik można podzielić porcji',
 'opakowanie zawiera porcji kostki',
 'opakowanie zawiera około porcje pełnowartościowych posiłków mleczno zbożowych',
 'porcja gałka gałka',
 'porcja opakowanie zawiera około porcji produktu',
 'wartość energetyczna produktu',
 'fenyloalanina produktu',
 'referencyjnych wartości spożycia',
 'tym poliole',
 'kwas foliowy rws',
 'gałka gałka',
 'kwasy tłuszczowe epa dha',
 'ilość porcji opakowaniu rozmiar porcji',
 'ryboflawina wit',
 'jedno opakowanie zawiera porcji ryżu',
 'produktu zawiera kwasów tłuszczowych omega',
 'wielkość porcji powinna być dostosowana wielu dziecka',
 'bez sztucznych barwników',
 'kwas linolowy',
 'kwas tłuszczowy omega',
 'kwas linolenowy',
 'siarczan cynku jednowodny',
 'siarczan manganu jednowodny',
 'siarczan miedzi pięciowodny',
 'ciasto można podzielić porcji porcja',
 'witamina rws',
 'opakowanie zawiera około sugerowanych porcji produktu',
 'ciasto można podzielić porcji',
 'opakowanie zawiera sugerowanych porcji produktu każda plastry',
 'opakowanie zawiera porcji jedna porcja mała garść produktu',
 'opakowanie zawiera porcji porcja ciastko około',
 'opakowanie wystarcza przygotowanie porcji galaretki',
 'opakowanie zawiera porcji produktu wafli',
 'ilość kromek',
 'nrv referencyjne wartości odżywcze',
 'błonnik pokarmowy',
 'porcja opakowanie zawiera porcji',
 'kwasy omega ala',
 'kwasy omega',
 'siarczan żelaza jednowodny',
 'jodek potasu',
 'selenian sodu',
 'nasycone wyłączeniem steroli',
 'zawartość wody',
 'opakowanie zawiera jedną porcję produktu',
 'wartości odżywcze',
 'miedź pentahydrat siarczanu miedzi',
 'dobatki sensoryczne',
 'cynk jako siarczan cynku monohydrat',
 'mangan jako siarczan manganu monohydrat monohydrat',
 'jod jako jodan wapnia',
 'surowe białko',
 'surowe oleje tłuszcze',
 'surowy popiół',
 'surowe włókno',
 'opakowanie zawiera porcje produktu porcja',
 'wartości odżywcze wyprażonym produkcie',
 'zawiera znikome ilości tłuszczu kwasów tłuszczowych nasyconych białka',
 'dzienne referencyjne wartości spożycia',
 'siarczan manganowy monohydrat',
 'regulator kwasowości',
 'wodorosiarczyn sodu',
 'porcja nestlé sinlac wody proszku',
 'referencyjna wartość spożycia referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal',
 'siarczyn cynku jednowodny',
 'witamina kwas askorbinowy',
 'jednej kapsułki przygotujesz napoju obliczenia dla nutriscore dokonano dla',
 'referencyjna wartość spożycia dla przeciętnej osoby doroslej kcal',
 'zawartość wilgoci',
 'opakowanie zawiera około ciastek czego każde',
 'surówki warmińskiej dostarcza rws',
 'nasycone',
 'opakowanie zawiera około porcji pełnowartościowych posiłków',
 'suma składników mineralnych',
 'biatko',
 'biało',
 'tym kwasy tłuszczowe',
 'miejsce urodzenia',
 'opakowanie zawiera około porcji produktu',
 'woda',
 'galatkooligosacharydy fruktooligosacharydy',
 'bez dodatku cukru zawiera naturalnie występujące cukry',
 'referencyjne wartości spożycia',
 'opakowanie zawiera porcje wielkość porcji powinna być dostosowana wieku dziecka',
 'włókno',
 'popiół',
 'pięciowodny siarczan miedzi',
 'referencyjna wartość spożycia dla przecietnej osoby dorosłej kcal',
 'butelka zawiera porcję produktu równą',
 'cholesterol',
 'enegia',
 'referencyjna wartość spożycia dla osoby dorosłej kcal',
 'produktu zawiera karnityny',
 'tłuszcz tym kwasy tłuszczowe',
 'kwasy omega epa',
 'kwasy omega dha',
 'sól zawartość wynikająca obecności naturalnie występującego sodu',
 'kwas cytrynowy',
 'butelka litrowa zawiera porcji',
 'opakowanie stanowi jedną sugerowaną porcję',
 'zawartość soli wynika wyłącznie obecności naturalnie występującego sodu mleku',
 'zawiera naturalnie występujące cukry cukier mleczny',
 'tym kwasy nasycone wyłączeniem steroli',
 'sterole roślinne',
 'porcji',
 'nasycone kwasy tłuszczowe',
 'chrom',
 'dziennej referencyjnej wartości spożycia',
 'suma składników mineralnyych',
 'jedno opakowanie zawiera sugerowanych porcji wegejajek',
 'opakowanie zawiera jedną sugerowaną porcję produktu',
 'opakowanie zawiera sugerowane porcje produktu każda plastrów',
 'porcja przyprawy opakowanie pozwala przygotowanie porcji',
 'przyrządzenia kostką litr',
 'wartość energetyczna enegia',
 'omega alfa linolenowy',
 'omega linolowy',
 'produkt może różnić się zawartością kwasów tłuszczowych zależności rodzaju nasion lnu patrz symbol przy partii',
 'zawartość laktozy produktu',
 'referencyjna wartość spozycia dla przeciętnej osoby dorosłej kcal',
 'ciastko opakowanie zawiera około ciastka',
 'opakowanie zawiera około porcje produktu porcja',
 'referencyjnej wartości spożycia dla osób dorosłych',
 'opakowanie bebilon pozwala przygotowanie około porcji napoju zgodnie tabelą żywienia',
 'porcja opakowanie zawiera porcji produktu',
 'referencyjnej wartości spożycia dla osoby dorosłej',
 'produktu zawiera guarany',
 'cynk siarczan cynku heptahydrat',
 'smak kurczaka',
 'jony',
 'sod',
 'niacina',
 'siarczany',
 'chlorki',
 'tym skrobia',
 'materia nieograniczona',
 'tłuszczowe jednonienasycone',
 'tłuszczowe wielonienasycone',
 'poliole',
 'kwas arachidonowy',
 'kwas eikozapentaenowy epa',
 'błonnik tym oligosacharydy',
 'gos galaktooligosacharydy',
 'fos fruktooligosacharydy',
 'fluorek',
 'cholina',
 'inozytol',
 'pozostałe oligosacharydy gos',
 'zawiera najmniej porcje',
 'tym tyrozyna',
 'tym leucyna',
 'tym ckry',
 'pole rezerwowe 40',
 'produkt zawiera porcje',
 'naturalna zawartość',
 'jod jodan potasu',
 'inki klasycznej około porcji',
 'dwóch kapsułek przygotujesz napoju obliczenia dla nurti score dokonano dla',
 'opakowanie zawiera porcję produktu przygotowaniu',
 'porcja łyżeczka',
 'witamina smaki rybne nie wzbogacone witaminę',
 'opakowanie pozwala przygotowanie porcji bulionetka porcje',
 'opakowanie zawiera około porcji gramowych',
 'ciasto można podzielić porcje porcja',
 'tym oligosacharydy',
 'nukleotydy',
 'opakowaniu znajdują się około porcje produktu',
 'dzienna referencyjna wartość spożyciaskładnikow mineralnych witamin dla osób dorosłych',
 'jedno opakowanie zawiera sugerowanych porcji',
 'opakowanie zawiera dwie porcje produktu',
 'zawartość kwasów tłuszczowych omega wynosi produktu',
 'dzienne referencyjne wartości spożycia witamin',
 'jednej kapsułki przygotujesz napoju obliczenia dla nutri score dokonano dla',
 'około',
 'smak łososia',
 'porcja około kremu',
 'przyrządzeniu kremu wystarcza przełożenie ciasta podzielenie porcje',
 'batonik porcja',
 'dzienna referencyjna wartość spożycia witamin składników mineralnych dla osoby dorosłej',
 'butelka zawiera około porcji',
 'produkt zawiera kostek',
 'hco',
 'sio',
 'łuszcz',
 'rws referencyjna wartość spożycia dla przeciętnej osoby dorosłej wynosi kcal',
 'litowy',
 'cynkowy',
 'selenowy',
 'kubek zawiera porcję produktu',
 'butelka zawiera około łyżek stołowych',
 'poszczególne wartości odżywcze mogą podlegać wahaniom względu naturalne pochodzenie składników',
 'materiał nieorganiczny',
 'zawartość składnika porcji dziennej',
 'ziele czystka cistus incanus',
 'produkt zawiera porcji kostka',
 'tłuszcz surowcowy',
 'kwasy tłuszczowe omega kwas linolenowy',
 'wafelek opakowaniu',
 'zawiera porcji',
 'oleje tłuszcze',
 'witamna',
 'jedno opakowanie zawiera porcji płatków',
 'średnia porcja',
 'dzienne referencyjna wartość spożycia witamin składników mineralnych dla osoby dorosłej',
 'ogólna zawartość soli mineralnych',
 'tym cukry ogółem',
 'opakowanie zawiera buteli',
 'zawartość składników odżywczych',
 'glukoza',
 'rws referencyjne wartości spożycia witamin składników mineralnych dla osób dorosłych',
 'cynk chelat cynkowy wodzianu glicyny tlenek cynku',
 'mangan siarczan manganu jednowodny',
 'tym tłuszcz nasycony',
 'rutyna',
 'tym cukier',
 'zawartość witamin',
 'wtamina',
 'liść morwy białej',
 'cynk jako jednowodny siarczan cynku',
 'mangan jako tlenek manganu',
 'miedź jako pentahydrat siarczanu miedzi',
 'jod jako bezwodny jodan wapnia',
 'opakowanie zawiera porcje wafle',
 'mineralizacja ogólna',
 'opakowanie zawiera sugerowanych porcji porcja sztuki',
 'taryna',
 'porcja lodów',
 'jedno opakowanie zawiera sugerowanych porcji burgerów',
 'referencyjne wartości spożycia witamin składników mineralnych dla osoby dorosłej',
 'dodatki żywieniowe',
 'elementy śladowe',
 'antyoksydanty',
 'popiuł surowy',
 'stanowi dziennej referencyjnej wartości spożycia',
 'porcję stanowi szt paróweczek',
 'włókna surowe',
 'wartość odżywcza',
 'tym alkohole wielowodorotlenowe',
 'dzienna referencyjna wartość spożycia witamin wapnia dla osoby dorosłej',
 'niacyna witamina',
 'podane wartości odżywcze dla porcji dotyczą masy netto produktu odsączeniu',
 'tłuszcz surowe',
 'składniki odżywcze',
 'rws referencyjne wartości spożycia',
 'tym kwasy tłuszczowe jedninienasycone',
 'mieszanki otrzymujemy szt babeczek porcja około',
 'miedź pentalnydrat siarczanu miedzi',
 'mangan tlenek manganu',
 'cynk jednowodny siarczan cynku',
 'opakowanie wystarcza przygotowania około porcji',
 'opakowanie zawiera około porcje',
 'wodorowęglanowy',
 'szczegoly dotyczace wina',
 'tym kwasy tuszczowe nasycone',
 'opakowanie zawiera sugerowane porcje produktu każda kabanosy',
 'dzienna referencyjna wartość spożycia witamin skladników mineralnych dla osób dorosłych',
 'dziennych referencyjnych wartości spożycia witamin składników mineralnych dla osób dorosłych',
 'kwas alfa linolenowy mega',
 'cynk tlenek cynku',
 'porcję wartość energetyczna kcal kcal referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal',
 'opakowanie zawiera porcji wafli',
 'magnez stanowi referencyjnej wartości spożycia',
 'opakwanie zawiera porcje',
 'jedno opakowanie zawiera porcji kaszy',
 'witamina cholekalcyferol',
 'obliczone dla zamrożonego produktu przygotowanego piekarniku zgodnie instrukcją przygotowania opakowaniu',
 'alkohole wielowodorotlenowe',
 'tym kwasy tłuszczowe nasyconebiałko',
 'opakowanie zawiera porcje ryżu',
 'okreslony obszar',
 'wynik nie uwzględnia soli dodanej podczas gotowania makaronu',
 'szklanka napoju dziennej referencyjnej wartości spożycia witaminy dla przeciętnej osoby dorosłej',
 'rws referencyjnych wartości spożycia',
 'jednej torebki można przyrządzić porcje budyniu',
 'magnez dri',
 'porcja odpowiada plasterek',

In [7]:
product_details.dropna(axis=1, inplace=True, thresh=5)
product_details.shape

(10261, 263)

In [8]:
product_details.columns.tolist()

['Unnamed: 0',
 'Referencja',
 'waga',
 'zalecenia dla alergikow',
 'opis produktu',
 'marka standaryzowana',
 'informacje dot stylu zycia',
 'jednostka opisowa',
 'kraj pochodzenia',
 'marka',
 'wartość energetyczna',
 'tłuszcz',
 'tym kwasy tłuszczowe nasycone',
 'węglowodany',
 'tym cukry',
 'białko',
 'sól',
 'przygotowanie',
 'błonnik',
 'uzytkowanie i przechowywanie',
 'nazwa produktu ureg prawnie',
 'podmarka',
 'dodatkowe informacje',
 'cechy',
 'dodatki',
 'wartość energetyczna kcal',
 'tłuszcz tym',
 'kwasy nasycone',
 'kwasy jednonienasycone',
 'kwasy wielonienasycone',
 'inne',
 'kwas alfa linolenowy omega',
 'sód',
 'zawartość soli wynika wyłącznie obecności naturalnie występującego sodu',
 'białka',
 'warunki przechowywania',
 'pole rezerwowe 20',
 'pochodzenie',
 'energia',
 'tym kwasy nasycone',
 'witamina',
 'rozszerzona nazwa produktu',
 'rws referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal',
 'Unnamed: 43',
 'kwasy tłuszczowe nasycone',
 'cukry',
 'wartość energetyczna energia kcal',
 'referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal',
 'magnezowy',
 'wapniowy',
 'sodowy',
 'potasowy',
 'aniony',
 'wodorowęglanowy hco',
 'siarczanowy',
 'chlorkowy',
 'fluorkowy',
 'wapń',
 'zawartość laktozy',
 'opakowanie zawiera sugerowaną porcję produktu',
 'dzienna referencyjna wartość spożycia wapnia dla osoby dorosłej',
 'opakowanie zawiera porcji',
 'zawartość tłuszczu',
 'materia nieorganiczna',
 'włókno surowe',
 'wilgotność',
 'smaki',
 'dodatki dietetyczne',
 'tauryna',
 'miedź pięciowodny siarczan miedzi',
 'jod jodan wapnia bezwodny',
 'żelazo siarczan żelaza jednowodny',
 'mangan siarczan manganawy jednowodny',
 'cynk siarczan cynku jednowodny',
 'dodatki technologiczne',
 'guma kasja',
 'opakowanie pozwala przygotowanie porcji',
 'referencyjnej wartości spożycia dla przeciętnej osoby dorosłej kcal',
 'kwasy tłuszczowe jednonienasycone',
 'kwasy tłuszczowe wielonienasycone',
 'rodzaj alkoholu',
 'miejsce uboju',
 'rozmiar porcji',
 'ilość porcji opakowaniu',
 'wit',
 'aromaty',
 'tłuszcz surowy',
 'popiół surowy',
 'kwasy tłuszczowe omega',
 'ryboflawina',
 'kwas foliowy',
 'węglowodany tym',
 'wielkość porcji powinna być dostosowana wieku dziecka',
 'opakowanie zawiera porcje',
 'tym nasycone kwasy tłuszczowe',
 'logotypy stron trzecich cd',
 'opakowanie zawiera porcji produktu',
 'opakowanie zawiera około porcje jedna porcja mała garść produktu',
 'referencyjna wartość spożycia',
 'cukry ogółem',
 'równoważna zawartość soli',
 'ilość porcji opakowania',
 'tłuszcze',
 'składnik',
 'cynk',
 'żelazo siarczan żelaza monohydrat',
 'mangan siarczan manganawy monohydrat',
 'cynk siarczan cynku monohydrat',
 'niacyna',
 'kwas pantotenowy',
 'opakowanie zawiera sugerowane porcje produktu',
 'opakowanie zawiera porcję produktu',
 'tłuszcze nasycone',
 'cukier',
 'jednonienasycone',
 'wielonienasycone',
 'omega kwas alfa linolenowy',
 'alkohole wielowodorotlenowe poliole',
 'tym kwasy tłuszczowe jednonienasycone',
 'tym kwasy tłuszczowe wielonienasycone',
 'witaminy składniki mineralne',
 'magnez',
 'fosfor',
 'dzienne referencyjne wartości spożycia witamin składników mineralnych dla osoby dorosłej',
 'opakowanie zawiera około porcji produktu porcja',
 'potas',
 'butelka zawiera porcję równą',
 'przeciwutleniacze barwniki',
 'żelazo',
 'rws referencyjna wartość spożycia',
 'jod jodek potasu',
 'butelka zawiera porcji',
 'witaminy',
 'tiamina',
 'opakowanie zawiera sugerowaną porcję',
 'tiamina witamina',
 'zalecanego dziennego spożycia',
 'informacja dla diabetyków produktu zawiera wbt',
 'referencyjnej wartości spożycia',
 'laktoza',
 'przeciwutleniacze konserwanty',
 'dodatki sensoryczne',
 'informacje dot stylu zycia cd',
 'tym fenyloalanina',
 'wartosc energetyczna',
 'tym nasycone',
 'siarczan żelaza monohydrat',
 'bezwodny jodan wapnia',
 'pentahydrat siarczanu miedzi',
 'siarczan manganawy monohydrat',
 'jednowodny siarczan cynku',
 'opakowanie zawiera butelki butelka zawiera porcję równą',
 'biotyna',
 'miedź pięciowodny siarczanu miedzi',
 'dostosuj wielkość porcji swoich potrzeb',
 'opakowanie zawiera porcji gramowych',
 'referencyjnej wartości spożycia dla dorosłych rozporządzenia',
 'nrv referencyjne wartości spożycia',
 'składniki mineralne',
 'dzienna referencyjna wartość spożycia witamin składników mineralnych dla osób dorosłych',
 'opakowanie zawiera porcję',
 'wartosc energetyczna kcal',
 'bialko',
 'weglowodany',
 'tluszcz',
 'tym kwasy tluszczowe nasycone',
 'sol',
 'konserwanty',
 'mangan',
 'miedź',
 'jod',
 'selen',
 'ekstrakt tokoferoli olejów roślinnych',
 'ekstrakt rozmarynu',
 'białko surowe',
 'opakowanie zawiera sugerowanych porcji produktu',
 'przeciwutleniacze',
 'barwniki',
 'selen selenin sodu',
 'zds zalecane dzienne spożycie',
 'tiamina wit',
 'kwas linolenowy ala',
 'witaminy grupy',
 'barwniki przeciwutleniacze',
 'kwasy tłuszczowe omega kwas linolowy',
 'kwas tłuszczowy omega kwas linolenowy',
 'blonnik',
 'wartość energetyczna energia',
 'zawiera naturalnie występujące cukry',
 'selenin sodu',
 'porcja lód',
 'dzienna referencyjna wartość spożycia witaminy wynosi',
 'procent referencyjnego dziennego spożycia witaminy',
 'porcja woreczka suchego produktu produktu ugotowaniu wodzie bez soli',
 'omega ala',
 'region pochodzenia',
 'porcja opakowanie pozwala przygotowanie porcji sosu',
 'siarczan zelaza monohydrat',
 'oleje tłuszcze surowe',
 'tym kwasy tłuszczowe nasycone kwasy nasycone',
 'produkt zawiera porcję',
 'opakowanie zawiera około porcji',
 'kwas dokozaheksaenowy dha',
 'porcje',
 'opakowanie zawiera porcje produktu',
 'karnityna',
 'składniki analityczne',
 'tym',
 'chlorek',
 'galaktozylolaktoza',
 'omega',
 'energia kcal',
 'zawartość soli wynika wyłącznie naturalnie występującego sodu',
 'produkt zawiera porcji kostki',
 'wodorowęglany',
 'witamina octan alfa tokoferylu',
 'miedź siarczan miedzi pięciowodny',
 'jod jodan wapnia',
 'fluorki',
 'dziennej referencyjnej wartości spożycia dla osoby dorosłej',
 'porcja gałka gałka',
 'referencyjnych wartości spożycia',
 'tym poliole',
 'gałka gałka',
 'kwas linolowy',
 'siarczan cynku jednowodny',
 'siarczan manganu jednowodny',
 'siarczan miedzi pięciowodny',
 'opakowanie zawiera około sugerowanych porcji produktu',
 'opakowanie zawiera porcji jedna porcja mała garść produktu',
 'wartości odżywcze',
 'miedź pentahydrat siarczanu miedzi',
 'cynk jako siarczan cynku monohydrat',
 'mangan jako siarczan manganu monohydrat monohydrat',
 'jod jako jodan wapnia',
 'surowe białko',
 'surowe oleje tłuszcze',
 'surowy popiół',
 'surowe włókno',
 'opakowanie zawiera porcje produktu porcja',
 'zawiera znikome ilości tłuszczu kwasów tłuszczowych nasyconych białka',
 'dzienne referencyjne wartości spożycia',
 'siarczan manganowy monohydrat',
 'siarczyn cynku jednowodny',
 'nasycone',
 'opakowanie zawiera około porcji pełnowartościowych posiłków',
 'tym kwasy tłuszczowe',
 'miejsce urodzenia',
 'butelka litrowa zawiera porcji',
 'nasycone kwasy tłuszczowe',
 'dziennej referencyjnej wartości spożycia',
 'opakowanie zawiera około porcje produktu porcja',
 'cynk siarczan cynku heptahydrat',
 'smak kurczaka',
 'jony',
 'tym skrobia',
 'kwas eikozapentaenowy epa',
 'fluorek',
 'cholina',
 'opakowanie zawiera około porcji gramowych',
 'dzienne referencyjne wartości spożycia witamin',
 'około',
 'cynk tlenek cynku']

In [9]:
product_details[product_details['tłuszcz surowy'].notna()]

,Unnamed: 0,Referencja,waga,zalecenia dla alergikow,opis produktu,marka standaryzowana,informacje dot stylu zycia,jednostka opisowa,kraj pochodzenia,marka,...,smak kurczaka,jony,tym skrobia,kwas eikozapentaenowy epa,fluorek,cholina,opakowanie zawiera około porcji gramowych,dzienne referencyjne wartości spożycia witamin,około,cynk tlenek cynku
70,70,129967,NaN,NaN,Pełnoporcjowa karma dla dorosłych kotów. Zapr...,Purina ONE,NaN,g,NaN,PURINA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432,432,608509,NaN,NaN,Pełnoporcjowa karma dla dorosłych kotów.,Gourmet,NaN,g,NaN,Gourmet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
521,521,15099,NaN,NaN,Butcher's z kurczakiem to pełnoporcjowa karma...,Butcher's,NaN,kg,Kraj pochodzenia - Wielka Brytania,Butcher's,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590,590,80404,NaN,NaN,Pełnoporcjowa karma dla dorosłych psów.,Friskies,NaN,kg,NaN,riskies,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
636,636,143592,NaN,NaN,Uzupełniająca karma dla dorosłych psów do cod...,Dentalife,NaN,g,NaN,Dentalife,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10123,10123,882978,NaN,NaN,Pełnoporcjowa karma dla dorosłych kotów. Karm...,Felix,NaN,g,NaN,Felix,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10124,10124,882980,NaN,NaN,Pełnoporcjowa karma dla dorosłych kotów. Karm...,Felix,NaN,g,NaN,Felix,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10125,10125,882991,NaN,NaN,Pełnoporcjowa karma dla dorosłych kotów. . Ka...,Felix,NaN,g,NaN,Felix,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10179,10179,971662,NaN,NaN,Karma uzupełniająca dla dorosłych kotów. biał...,Felix,NaN,g,NaN,Felix,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10260,10260,998676,NaN,NaN,PURINA® ONE® Coat & Hairball została zaprojek...,Purina ONE,NaN,g,NaN,PURINA ONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
mapping = {
    "zawartość tłuszczu": "tłuszcz",
    "tłuszcz tym": "tłuszcz",
    "tluszcz": "tłuszcz",
    "tłuszcze": "tłuszcz",
    "tuszcz": "tłuszcz",

    "bialko": "białko",
    "białka": "białko",

    "węglowodany tym": "węglowodany",
    "weglowodany": "węglowodany",

    "tym cukry": "cukry",
    "cukry ogółem": "cukry",
    "cukier": "cukry",

    "energia": "wartość energetyczna",
    "wartość energetyczna kcal": "wartość energetyczna",
    "wartość energetyczna energia kcal": "wartość energetyczna",
    "wartosc energetyczna": "wartość energetyczna",
    "wartosc energetyczna kcal": "wartość energetyczna",
    "blonnik": "wartość energetyczna",
    "wartość energetyczna energia": "wartość energetyczna",
    "energia kcal": "wartość energetyczna",

    "sol": "sól",
}

In [11]:
# Standardizing column names 

for source_col, target_col in mapping.items():
    if source_col in product_details.columns:
        product_details[target_col] = product_details[target_col].combine_first(product_details[source_col])

cols_to_drop = [col for col in product_details.columns if col in mapping]
product_details = product_details.drop(columns=cols_to_drop)

In [12]:
print(product_details.isna().sum().tolist())

[0, 0, 6552, 5951, 4716, 5678, 8959, 5249, 5492, 1593, 4536, 4391, 5563, 4456, 4281, 4595, 9342, 8018, 8822, 2555, 8717, 8845, 7110, 8538, 10185, 10247, 10247, 10227, 10247, 10160, 10225, 8469, 9940, 9245, 9544, 9678, 9435, 10155, 9895, 10133, 4499, 9668, 10244, 10244, 10244, 10246, 10256, 10254, 10251, 10251, 10251, 9984, 10251, 10250, 10255, 10157, 10156, 9994, 10081, 10251, 10037, 10134, 10194, 10206, 10193, 10177, 10178, 10205, 10224, 10241, 10197, 10238, 10238, 10248, 10136, 10250, 10250, 10179, 10208, 10141, 10105, 10182, 10193, 10197, 10239, 10198, 10240, 10131, 10238, 10256, 10237, 10200, 10256, 10253, 10193, 10256, 10252, 10255, 10139, 10174, 10205, 10250, 10254, 10226, 10226, 10256, 10249, 10239, 10238, 10231, 10158, 10159, 10247, 10255, 10214, 10248, 10246, 10171, 10253, 10225, 10246, 10174, 10198, 10253, 10253, 10250, 10249, 10244, 10244, 10253, 10244, 10245, 10255, 10246, 10221, 10201, 10214, 10217, 10207, 10254, 10185, 10244, 10248, 10254, 10246, 10256, 10196, 10253, 10230, 10230, 10250, 10228, 10238, 10211, 10243, 10256, 10256, 10236, 10247, 10210, 10251, 10236, 10252, 10252, 10236, 10251, 10250, 10253, 10255, 10253, 10239, 10254, 10252, 10252, 10256, 10253, 10251, 10254, 10254, 10250, 10251, 10253, 10255, 10255, 10254, 10252, 10255, 10224, 10235, 10253, 10254, 10255, 10255, 10255, 10251, 10256, 10250, 10256, 10253, 10250, 10256, 10251, 10255, 10255, 10255, 10253, 10248, 10248, 10250, 10255, 10256, 10255, 10255, 10255, 10255, 10255, 10255, 10255, 10255, 10255, 10249, 10249, 10251, 10256, 10255, 10256, 10256, 10241, 10251, 10256, 10256, 10255, 10255, 10255, 10256, 10255, 10256, 10256, 10256, 10255, 10255, 10252, 10256]

In [13]:
product_details.shape

(10261, 243)

In [14]:
cols_to_drop = [col for col in product_details.columns if product_details[col].isna().sum() > 10000]

product_details = product_details.drop(columns=cols_to_drop)

In [15]:
product_details.shape

(10261, 35)

In [16]:
product_details.head()

,Unnamed: 0,Referencja,waga,zalecenia dla alergikow,opis produktu,marka standaryzowana,informacje dot stylu zycia,jednostka opisowa,kraj pochodzenia,marka,...,pole rezerwowe 20,pochodzenie,tym kwasy nasycone,witamina,rozszerzona nazwa produktu,Unnamed: 43,cukry,referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal,wapń,włókno surowe
0,0,97,Waga brutto - 20 g,"ORZECHY - Może zawierać, ORZESZKI ZIEMNE - Mo...",Odpowiedni dla Wegetarian i Wegan.,Blue Dragon,"Produkt odpowiedni dla wegan, Produkt odpowie...",g,Kraj pochodzenia - Korea (Republika Korei),Blue Dragon,...,NaN,NaN,NaN,NaN,NaN,NaN,"6,2 g",NaN,NaN,NaN
1,1,143,Waga brutto - 512 g,"ORZECHY - Może zawierać, ORZESZKI ZIEMNE - Mo...",Odpowiedni dla Wegetarian i Wegan.,Blue Dragon,"Produkt odpowiedni dla wegan, Produkt odpowie...",g,Zapakowano w - Wielka Brytania,Blue Dragon,...,NaN,NaN,NaN,NaN,NaN,NaN,"0,3 g",NaN,NaN,NaN
2,2,1864,80 g,Może zawierać śladowe ilości,Roślinne plastry,NaN,NaN,NaN,Rumunia,Verdino,...,NaN,NaN,NaN,NaN,NaN,NaN,"6,4 g",NaN,NaN,NaN
3,3,7441,NaN,NaN,Blue Ocean. Kostka odświeżająca i czyszcząca ...,NaN,NaN,g,Wyprodukowano w Polsce,Kolorado,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,8499,NaN,"Może zawierać SOJĘ, GORCZYCĘ, SELER, MLEKO, R...",NaN,NaN,NaN,g,Wyprodukowano w Polsce,Taverna Dell'Ancora,...,NaN,NaN,NaN,NaN,NaN,NaN,"0,1 g",NaN,NaN,NaN

In [17]:
print(product_details.isna().sum())

Unnamed: 0                                                              0
Referencja                                                              0
waga                                                                 6552
zalecenia dla alergikow                                              5951
opis produktu                                                        4716
marka standaryzowana                                                 5678
informacje dot stylu zycia                                           8959
jednostka opisowa                                                    5249
kraj pochodzenia                                                     5492
marka                                                                1593
wartość energetyczna                                                 4536
tłuszcz                                                              4391
tym kwasy tłuszczowe nasycone                                        5563
węglowodany                                                          4456
białko                                                               4281
sól                                                                  4595
przygotowanie                                                        9342
błonnik                                                              8018
uzytkowanie i przechowywanie                                         8822
nazwa produktu ureg prawnie                                          2555
podmarka                                                             8717
dodatkowe informacje                                                 8845
cechy                                                                7110
dodatki                                                              8538
warunki przechowywania                                               8469
pole rezerwowe 20                                                    9940
pochodzenie                                                          9245
tym kwasy nasycone                                                   9544
witamina                                                             9678
rozszerzona nazwa produktu                                           9435
Unnamed: 43                                                          9895
cukry                                                                4499
referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal    9668
wapń                                                                 9984
włókno surowe                                                        9994
dtype: int64

In [18]:
cols_to_drop = ['Unnamed: 0',
                'zalecenia dla alergikow',
                'uzytkowanie i przechowywanie',
                'informacje dot stylu zycia', 
                'dodatkowe informacje',
                'dodatki',
                'uzytkowanie i przechowywanie',
                'tym kwasy tłuszczowe nasycone',
                'warunki przechowywania',
                'cechy']
product_details = product_details.drop(columns=cols_to_drop)

In [19]:
product_details['Referencja'] = product_details['Referencja'].apply(str)

In [20]:
product_details.head()

,Referencja,waga,opis produktu,marka standaryzowana,jednostka opisowa,kraj pochodzenia,marka,wartość energetyczna,tłuszcz,węglowodany,...,pole rezerwowe 20,pochodzenie,tym kwasy nasycone,witamina,rozszerzona nazwa produktu,Unnamed: 43,cukry,referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal,wapń,włókno surowe
0,97,Waga brutto - 20 g,Odpowiedni dla Wegetarian i Wegan.,Blue Dragon,g,Kraj pochodzenia - Korea (Republika Korei),Blue Dragon,1481 kJ/348 kcal,"<0,1 g",41 g,...,NaN,NaN,NaN,NaN,NaN,NaN,"6,2 g",NaN,NaN,NaN
1,143,Waga brutto - 512 g,Odpowiedni dla Wegetarian i Wegan.,Blue Dragon,g,Zapakowano w - Wielka Brytania,Blue Dragon,1469 kJ/346 kcal,"1,0 g","77,2 g",...,NaN,NaN,NaN,NaN,NaN,NaN,"0,3 g",NaN,NaN,NaN
2,1864,80 g,Roślinne plastry,NaN,NaN,Rumunia,Verdino,994 kJ / 240 kcal,"20,4 g","7,1 g",...,NaN,NaN,NaN,NaN,NaN,NaN,"6,4 g",NaN,NaN,NaN
3,7441,NaN,Blue Ocean. Kostka odświeżająca i czyszcząca ...,NaN,g,Wyprodukowano w Polsce,Kolorado,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8499,NaN,NaN,NaN,g,Wyprodukowano w Polsce,Taverna Dell'Ancora,279 kcal,"5,1 g","45,8 g",...,NaN,NaN,NaN,NaN,NaN,NaN,"0,1 g",NaN,NaN,NaN

In [21]:
product_details['waga'] = product_details['waga'].apply(lambda x: re.search(r"\d+\.?\d*", x).group() if isinstance(x, str) and re.search(r"\d+\.?\d*", x) else None)
product_details['waga'] = product_details['waga'].apply(pd.to_numeric)

In [22]:
product_details['kraj pochodzenia'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 10261 entries, 0 to 10260
Series name: kraj pochodzenia
Non-Null Count  Dtype
--------------  -----
4769 non-null   object
dtypes: object(1)
memory usage: 80.3+ KB

In [23]:
# translator = GoogleTranslator(source='auto', target='en')

In [24]:
# product_details['kraj pochodzenia EN'] = product_details['kraj pochodzenia'].apply(lambda x: translator.translate(x) if isinstance(x, str) else None)

In [25]:
# product_details['kraj pochodzenia EN']

In [26]:
# import nltk
# nltk.downloader.download('maxent_ne_chunker')
# nltk.downloader.download('words')
# nltk.downloader.download('treebank')
# nltk.downloader.download('maxent_treebank_pos_tagger')
# nltk.downloader.download('punkt')
# nltk.download('averaged_perceptron_tagger_eng')
# nltk.download('maxent_ne_chunker_tab')

In [27]:
# import geograpy
# import nltk
# nltk.download('punkt')
# nltk.download('averaged_perceptron_tagger')
# nltk.download('maxent_ne_chunker')
# nltk.download('words')

In [28]:
# product_details['kraj'] = product_details['kraj pochodzenia EN'].apply(lambda x: geograpy.get_geoPlace_context(text = x).countries if isinstance(x, str) else None)

# # product_details['kraj pochodzenia'] = product_details['kraj pochodzenia'].apply(lambda x: x.strip().lower().replace('kraj pochodzenia', '') if isinstance(x, str) else None)
# # product_details['kraj pochodzenia'] = product_details['kraj pochodzenia'].apply(lambda x: x.strip().lower().replace('wyprodukowano w ', '') if isinstance(x, str) else None)

In [29]:
# product_details['kraj'].value_counts()

In [30]:
product_details = product_details.drop(columns=['nazwa produktu ureg prawnie', 'pochodzenie', 'podmarka'])

In [31]:
product_details.head()

,Referencja,waga,opis produktu,marka standaryzowana,jednostka opisowa,kraj pochodzenia,marka,wartość energetyczna,tłuszcz,węglowodany,...,błonnik,pole rezerwowe 20,tym kwasy nasycone,witamina,rozszerzona nazwa produktu,Unnamed: 43,cukry,referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal,wapń,włókno surowe
0,97,20.0,Odpowiedni dla Wegetarian i Wegan.,Blue Dragon,g,Kraj pochodzenia - Korea (Republika Korei),Blue Dragon,1481 kJ/348 kcal,"<0,1 g",41 g,...,NaN,NaN,NaN,NaN,NaN,NaN,"6,2 g",NaN,NaN,NaN
1,143,512.0,Odpowiedni dla Wegetarian i Wegan.,Blue Dragon,g,Zapakowano w - Wielka Brytania,Blue Dragon,1469 kJ/346 kcal,"1,0 g","77,2 g",...,"1,3 g",NaN,NaN,NaN,NaN,NaN,"0,3 g",NaN,NaN,NaN
2,1864,80.0,Roślinne plastry,NaN,NaN,Rumunia,Verdino,994 kJ / 240 kcal,"20,4 g","7,1 g",...,"3,1 g",NaN,NaN,NaN,NaN,NaN,"6,4 g",NaN,NaN,NaN
3,7441,NaN,Blue Ocean. Kostka odświeżająca i czyszcząca ...,NaN,g,Wyprodukowano w Polsce,Kolorado,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8499,NaN,NaN,NaN,g,Wyprodukowano w Polsce,Taverna Dell'Ancora,279 kcal,"5,1 g","45,8 g",...,NaN,NaN,NaN,NaN,NaN,NaN,"0,1 g",NaN,NaN,NaN

In [32]:
product_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10261 entries, 0 to 10260
Data columns (total 23 columns):
 #   Column                                                             Non-Null Count  Dtype
---  ------                                                             --------------  -----
 0   Referencja                                                         10261 non-null  object
 1   waga                                                               3676 non-null   float64
 2   opis produktu                                                      5545 non-null   object
 3   marka standaryzowana                                               4583 non-null   object
 4   jednostka opisowa                                                  5012 non-null   object
 5   kraj pochodzenia                                                   4769 non-null   object
 6   marka                                                              8668 non-null   object
 7   wartość energetyczna                                               5725 non-null   object
 8   tłuszcz                                                            5870 non-null   object
 9   węglowodany                                                        5805 non-null   object
 10  białko                                                             5980 non-null   object
 11  sól                                                                5666 non-null   object
 12  przygotowanie                                                      919 non-null    object
 13  błonnik                                                            2243 non-null   object
 14  pole rezerwowe 20                                                  321 non-null    object
 15  tym kwasy nasycone                                                 717 non-null    object
 16  witamina                                                           583 non-null    object
 17  rozszerzona nazwa produktu                                         826 non-null    object
 18  Unnamed: 43                                                        366 non-null    object
 19  cukry                                                              5762 non-null   object
 20  referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal  593 non-null    object
 21  wapń                                                               277 non-null    object
 22  włókno surowe                                                      267 non-null    object
dtypes: float64(1), object(22)
memory usage: 1.8+ MB

In [33]:
cols_to_standardize = ['tłuszcz', 'węglowodany', 'białko', 'sól', 'błonnik', 'cukry']

In [34]:
product_details.head()

,Referencja,waga,opis produktu,marka standaryzowana,jednostka opisowa,kraj pochodzenia,marka,wartość energetyczna,tłuszcz,węglowodany,...,błonnik,pole rezerwowe 20,tym kwasy nasycone,witamina,rozszerzona nazwa produktu,Unnamed: 43,cukry,referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal,wapń,włókno surowe
0,97,20.0,Odpowiedni dla Wegetarian i Wegan.,Blue Dragon,g,Kraj pochodzenia - Korea (Republika Korei),Blue Dragon,1481 kJ/348 kcal,"<0,1 g",41 g,...,NaN,NaN,NaN,NaN,NaN,NaN,"6,2 g",NaN,NaN,NaN
1,143,512.0,Odpowiedni dla Wegetarian i Wegan.,Blue Dragon,g,Zapakowano w - Wielka Brytania,Blue Dragon,1469 kJ/346 kcal,"1,0 g","77,2 g",...,"1,3 g",NaN,NaN,NaN,NaN,NaN,"0,3 g",NaN,NaN,NaN
2,1864,80.0,Roślinne plastry,NaN,NaN,Rumunia,Verdino,994 kJ / 240 kcal,"20,4 g","7,1 g",...,"3,1 g",NaN,NaN,NaN,NaN,NaN,"6,4 g",NaN,NaN,NaN
3,7441,NaN,Blue Ocean. Kostka odświeżająca i czyszcząca ...,NaN,g,Wyprodukowano w Polsce,Kolorado,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8499,NaN,NaN,NaN,g,Wyprodukowano w Polsce,Taverna Dell'Ancora,279 kcal,"5,1 g","45,8 g",...,NaN,NaN,NaN,NaN,NaN,NaN,"0,1 g",NaN,NaN,NaN

In [35]:
for col in cols_to_standardize:
    product_details[col] = product_details[col].apply(lambda x: x.lower().replace("g", "").replace(",", ".").replace("<0.5", "0").replace("<0.1", "0").replace("-", "0").strip() if isinstance(x, str) else None)

In [36]:
for col in cols_to_standardize:
    product_details[col] = (
    product_details[col]
      .astype(str)
      .str.replace(',', '.', regex=False)
      .str.extract(r'([-+]?\d*\.?\d+)')[0]
      .astype(float)
      .round(2)
)

In [37]:
product_details['wartość energetyczna'].to_list()

['1481 kJ/348 kcal',
 '1469 kJ/346 kcal',
 '994 kJ / 240 kcal',
 nan,
 '279 kcal',
 nan,
 nan,
 nan,
 '6 kJ / 1 kcal',
 nan,
 '275/66',
 '2847 kJ/690 kcal',
 nan,
 '163KJ/63 KCAL',
 '155 kJ (37 kcal)',
 nan,
 nan,
 '952 kJ/230 kcal',
 '2403 kJ/ 580 Kcal',
 '2666 kJ / 637 kcal',
 nan,
 nan,
 '591 kJ / 139 kcal',
 nan,
 nan,
 nan,
 nan,
 nan,
 '142 kJ/ 34 Kcal',
 '85 kJ / 20 kcal',
 nan,
 nan,
 '480 kJ/ 115 kcal',
 '945 kJ/ 227 kcal',
 'kcal 254',
 '2360/566',
 '191 kJ/46 kcal',
 nan,
 nan,
 '1630kJ/390 kcal',
 '597 kJ / 143 kcal',
 nan,
 '37 kcal',
 '297 kJ / 71 kcal',
 nan,
 nan,
 '1700 kJ / 400 kcal',
 '1857/444',
 '1627 kJ/ 383 kcal',
 '2399 kJ/578 kcal',
 nan,
 nan,
 '496 kcal',
 '2280 kJ/ 546 Kcal',
 '213 kJ / 51 kcal',
 nan,
 '3389 kJ / 824 kcal',
 '1236 kJ/ 291 Kcal',
 '1248 kj / 295 kcal',
 '294 kJ / 71 kcal',
 nan,
 ' 78 kJ / 18 kcal',
 '2807 kJ / 683 kcal',
 nan,
 nan,
 '1589 kJ / 384 kcal',
 '577 kJ/ 138 Kcal',
 nan,
 nan,
 '445 kcal',
 nan,
 '186 kJ / 44 kcal',
 nan,
 nan,
 '435 kJ / 102 kcal',
 '596 kJ/143 kcal',
 nan,
 '2898 kJ / 704 kcal',
 '22 kcal',
 nan,
 nan,
 '834 kJ / 199 kcal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '475 kJ / 113 kcal',
 nan,
 nan,
 nan,
 nan,
 '1667 kJ / 395 kcal',
 nan,
 '253 kJ / 60 kcal',
 '2360/566',
 nan,
 nan,
 '6 kJ/1 kcal',
 '1810kJ / 430kcal',
 '225kJ/531 kcal,',
 '337 kJ / 80 kcal',
 '1646 kJ/387 kcal',
 nan,
 nan,
 '884 kJ/ 211 Kcal',
 '1283 kj / 309 kcal',
 nan,
 '947 kJ / 228 kcal',
 '1029 kJ / 247 kcal',
 '1008 kJ / 242 kcal',
 '114 kcal',
 nan,
 '1526 kJ/3645 kcal',
 nan,
 '1073 kJ/ 260 kcal',
 nan,
 nan,
 nan,
 '776 kJ/187 kcal',
 '1 436 kJ/338 kcal',
 nan,
 '1670 kJ',
 '386 kJ / 92 kcal',
 nan,
 nan,
 '489 kJ / 117 kcal',
 nan,
 nan,
 nan,
 '541 kJ/ 128 kcal',
 nan,
 nan,
 nan,
 '534 kcal',
 nan,
 nan,
 '1026 kJ',
 '1531 kJ / 361 kcal',
 '113 kJ/27 kcal',
 nan,
 nan,
 nan,
 nan,
 '1326 kJ/ 316 Kcal',
 '564 kJ / 137 kcal',
 nan,
 '743 kJ/177 kcal',
 nan,
 '151 kJ / 36 kcal',
 '70 kcal',
 nan,
 '1623 kJ/383 kcal',
 '423 kcal',
 '669 kJ/ 158 Kcal',
 nan,
 nan,
 nan,
 nan,
 '335 kJ / 79 kcal',
 '630 kJ/151 kcal',
 '173 kJ / 42 kcal',
 '1671 kJ / 402 kcal',
 '3404 kJ/ 828 kcal',
 '424 kJ / 101 kcal',
 '764 kJ/ 185 Kcal',
 '1267 kJ/299 kcal',
 '1901 kJ',
 '346 kcal',
 nan,
 '1029 kJ/ 248 kcal',
 '460 kcal',
 '1881 kJ / 447 kcal',
 '2249 kJ  539 kcal',
 '1514 kJ / 356 kal',
 nan,
 '441 kJ / 100 kcal',
 nan,
 nan,
 nan,
 nan,
 '2281 kJ / 554 kcal',
 nan,
 '497 kJ/ 118 Kcal',
 '256 kcal',
 nan,
 '464 kJ / 110 kcal',
 '113 kJ / 27 kcal',
 nan,
 '2312 kJ / 553 kcal',
 nan,
 nan,
 nan,
 '24 kcal',
 '1989 kJ / 475 kcal',
 nan,
 '424 kJ/101 kcal',
 '777 kJ / 188 kcal',
 '559 kJ / 135 kcal',
 nan,
 '2284 kJ / 548 kcal',
 '2149 kJ',
 nan,
 nan,
 '216 kJ/ 51 Kcal',
 '353 kcal/100 g',
 '2165 kJ/ 519 Kcal',
 '1006 kJ/239 kcal',
 '361 kcal',
 '1461 kj /352 kcal',
 '163KJ/63 KCAL',
 '2206 kJ/537 kcal',
 '1495 kJ / 354 kcal',
 nan,
 nan,
 nan,
 ' 330 kJ / 78 kcal',
 '888 kJ/ 210 Kcal',
 '1920 kJ/464 kcal',
 '1989',
 '598 kcal',
 nan,
 nan,
 '39 kcal',
 nan,
 '1479 kJ / 348 kcal',
 nan,
 nan,
 nan,
 '176kcal',
 '777 kJ / 185 kcal',
 '19 kcal',
 '1247 kJ / 295 kcal',
 nan,
 nan,
 '352 kJ/ 84 Kcal',
 nan,
 ' 211 kJ / 50 kcal',
 ' 158 kJ / 38 kcal',
 '1407 kJ/332 kcal',
 '1487 kJ / 351 kcal',
 '16 kcal',
 '261 kJ / 62 kcal',
 nan,
 '584 kcal',
 nan,
 nan,
 nan,
 '1481 kJ / 354 kcal',
 nan,
 nan,
 '241 kcal',
 nan,
 '943 kJ / 227 kcal',
 '346 kcal',
 '2132 kJ/511 kcal',
 '2001 kJ/ 477 kcal ',
 '597 kJ / 145 kcal',
 nan,
 nan,
 nan,
 '1163 kJ/ 280 kcal',
 nan,
 nan,
 nan,
 nan,
 '259 kJ / 61 kcal',
 nan,
 '320 kJ / 75 kcal',
 nan,
 nan,
 nan,
 nan,
 nan,
 '780 kJ/ 184 Kcal',
 nan,
 '471 kJ / 112 kcal',
 nan,
 '225 kJ / 51 kcal',
 '1901 / 455',
 nan,
 '86 kJ / 20 kcal',
 nan,
 '1545 kJ (368 kcal)',
 nan,
 '2596 kJ / 631 kcal',
 '601 kJ/ 144 kcal',
 nan,
 nan,
 nan,
 '954 kJ/ 229 Kcal',
 nan,
 '416 kcal/100 g',
 nan,
 nan,
 '82,9/19,8',
 nan,
 '2114 kJ/508 kcal',
 '1150 kJ/272 kcal',
 ' 973 kJ (232 kcal)',
 '1738 kJ /416 kcal',
 nan,
 '960 kJ / 229 kcal',
 nan,
 '1884/450',
 nan,
 nan,
 '1126 kJ/267 kcal',
 nan,
 '1881 kJ',
 '1493/354',
 '479 kJ / 114 kcal',
 '433 kJ/ 103 kcal',
 '412 kcal',
 nan,
 '513 kJ/ 121 Kcal',
 nan,
 nan,
 nan,
 ' 245 kJ / 58 kcal',
 nan,
 '1918 kJ / 464 kcal',
 '2454 kJ/591 kcal',
 nan,
 '1807 kJ  / 428 kcal',
 nan,
 '1440 KJ/ 341 Kcal',
 '63 kcal',
 nan,
 nan,
 '530 kJ/ 129 Kcal',
 '1461 kJ / 352 kcal',
 '2016 kJ/ 480 Kcal',
 '225 kJ / 53 kcal',
 '56,6 kcal',
 nan,
 nan,
 'PRZECHOWYWAĆ W SUCHYM CHŁODNYM MIEJSCU',
 nan,
 '1330 kJ / 316 kcal',
 nan,
 '951 kJ (245 kcal)',
 '585/141 (kJ/kcal)',
 '912 kJ / 218 kcal',
 '317/76',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '82 kJ/ 20 Kcal',
 '1627 kJ/ 393 Kcal',
 '261 kJ / 62 kcal',
 '100 kJ/24 kcal',
 '577 kJ/138 kcal',
 '1038 kJ / 248 kcal',
 '383 kJ / 90 kcal',
 '442 kJ / 105 kcal',
 '1134 kJ / 273 kcal',
 '358 kJ / 85 kcal',
 '155 kJ / 36 kcal',
 nan,
 '1004 kJ / 243 kcal',
 '442 kJ / 105 kcal',
 nan,
 '92 kJ/ 22 Kcal',
 '963 kJ / 232 kcal',
 '686 kJ/ 167 Kcal',
 nan,
 nan,
 '302 kcal/100 g',
 nan,
 nan,
 '1772 kJ/420 kcal',
 nan,
 nan,
 '947 kJ / 227 kcal',
 nan,
 '1631 kJ / 386 kcal',
 '2151 kJ/ 519 kcal',
 nan,
 '1566 kJ /371 kcal',
 '2828 kJ/687 kcal',
 '565 kcal',
 '2380/571',
 '64 kcal',
 '409 kJ / 96 kcal',
 nan,
 '1659 kJ / 391 kcal',
 '125 kJ/30 kcal',
 nan,
 nan,
 '2237 kJ / 537 kcal ',
 nan,
 nan,
 nan,
 nan,
 '963 kJ / 227 kcal',
 nan,
 nan,
 nan,
 nan,
 nan,
 '1037 kJ/ 250 Kcal',
 nan,
 '1779 kJ / 431 kcal',
 nan,
 '825 kJ/ 195 Kcal',
 nan,
 '1824/433',
 nan,
 '1502 kJ / 355 kcal',
 nan,
 '645 kJ / 154 kcal',
 '1413 kJ / 337 kcal',
 nan,
 nan,
 nan,
 nan,
 nan,
 '341 kcal',
 '323',
 nan,
 '530 kcal',
 nan,
 nan,
 nan,
 '440 kJ / 105 kcal',
 ' 320 kJ / 76 kcal',
 '306 kJ / 72 kcal',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '526 kcal',
 '609 kJ / 144 kcal',
 '1231 kJ/ 291 kcal',
 '74 kJ / 18 kcal',
 '1127kJ/273kcal',
 nan,
 '1543 KJ / 374 kcal',
 '1536 kj/ 367 kcal',
 '936 kJ/ 225 kcal',
 nan,
 nan,
 nan,
 '2381 kJ / 572 kcal',
 '397 kcal',
 '522 kcal',
 '81 KJ/ 19 Kcal',
 '83 kJ / 20 kcal',
 '180 kJ / 42 kcal',
 '183 kJ / 43 kcal',
 '81 kJ / 19 kcal',
 '0,9 kJ / 0,2 kcal',
 '158 kJ / 37 kcal',
 nan,
 nan,
 nan,
 '1420 kJ / 339 kcal',
 nan,
 nan,
 nan,
 nan,
 nan,
 '244 kcal',
 '605 kJ / 142 kcal',
 nan,
 '1615 kJ / 381 kcal',
 nan,
 nan,
 '29 kcal',
 '1658 kJ / 403 kcal',
 nan,
 nan,
 nan,
 nan,
 '1928 kJ ',
 '1478 kJ/ 353 Kcal',
 nan,
 '391 kcal',
 nan,
 '2060 kJ/493 kcal',
 '1842 kJ/440 kcal',
 '405 kJ/ 96 kcal',
 '1307 kJ/ 312 Kcal',
 '2366 kJ / 572 kcal',
 nan,
 nan,
 nan,
 nan,
 '1531 kJ/ 366 Kcal',
 '568 kJ / 135 kcal',
 nan,
 '77 kJ/18 kcal',
 '153 kJ/ 37 Kcal',
 nan,
 '2535 kJ/612 kcal',
 '192 kJ / 46 kcal',
 '180 kcal (763 kJ)',
 '763 kJ/180 Kcal',
 nan,
 '1463 kJ/346 kcal',
 nan,
 '1190 kJ / 285 kcal',
 '138 kcal',
 nan,
 nan,
 '697 kj / 166 kcal',
 '2965 kJ / 721 kcal',
 '293 kcal/100 g',
 '734 kJ / 174 kcal',
 nan,
 nan,
 nan,
 '106 kJ/ 25 Kcal',
 ' 382 kJ / 91 kcal',
 '494 kJ/116 kcal',
 '1450 kJ/341 kcal',
 '176 kJ / 41 kcal',
 nan,
 '220 kJ / 52 kcal',
 '2048 kJ / 488 kcal',
 nan,
 '669 kJ/158 kcal',
 '2107 kJ / 506 kcal',
 nan,
 '1998 kJ',
 nan,
 '709 kJ / 167 kcal',
 '1289 kJ/313 kcal',
 '668 kJ / 160 kcal',
 '1442 kJ / 340 kcal',
 '379 kcal/100 g',
 nan,
 nan,
 nan,
 '97 kJ / 23 kcal',
 nan,
 '2 kJ / 0 kcal',
 '416 kcal / 100 g',
 nan,
 nan,
 nan,
 '365 kcal',
 '325 kJ/78 kcal',
 '155 kJ - 37 kcal',
 nan,
 ' 191 kJ / 46 kcal',
 nan,
 '295 kJ / 70 kcal',
 '318 kJ / 75 kcal',
 nan,
 nan,
 nan,
 nan,
 '2008 kJ',
 '48 kcal',
 nan,
 nan,
 nan,
 '1211 KJ/291 kcal',
 '215 kJ/ 51 kcal',
 nan,
 nan,
 ' 1092 kJ (262 kcal)',
 '222/53 kJ/kcal',
 nan,
 '341 kJ = 83 kcal',
 '83 kJ / 20 kcal',
 '1801',
 nan,
 nan,
 '2552 kJ / 615 kcal',
 nan,
 '37 kcal',
 '255 kJ/61 kcal',
 '193 kJ/46 kcal',
 nan,
 'nd',
 nan,
 nan,
 nan,
 '914 kJ',
 nan,
 '90 kJ / 21 kcal',
 '970 kJ/ 233 Kcal ',
 '117 kJ/ 28 Kcal',
 '158 kJ/ 37 Kcal',
 '622 kJ / 149 kcal',
 '2600 kJ / 627 kcal',
 '837 kJ/ 202 Kcal',
 '2807 kJ / 683 kcal',
 nan,
 nan,
 '1426 kJ / 346 kcal',
 '243 kJ/ 58 Kcal',
 nan,
 '288 kJ/ 69 kcal',
 nan,
 nan,
 '1229 kJ/290 kcal',
 nan,
 '1124 kj / 265 kcal',
 '194 kJ/46 kcal',
 '1803',
 '1421 kJ / 336 kcal',
 '313 kJ/75 kcal',
 '132 kJ/31 kcal',
 '189 kJ / 45 kcal',
 '1191 kJ/ 288 Kcal',
 nan,
 '455 kJ / 108 kcal',
 '1525 kJ / 360 kcal',
 '595 kJ / 142 kcal',
 '379 kJ / 90 kcal',
 '1374 kJ ',
 '1594 kJ/379 kcal',
 nan,
 '2965 kJ / 721 kcal',
 '2342 kJ/561 kcal',
 nan,
 '1481 kJ/ 358 kcal',
 '45',
 nan,
 '1344,7 kJ/ 316,4 Kcal',
 '2176 kJ/ 520 Kcal',
 '1344,7 kJ/ 316,4 Kcal',
 nan,
 '764 kJ/182 kcal',
 '305 kcal',
 '352 kJ/82 kcal',
 nan,
 nan,
 '2272 kJ / 543 kcal',
 nan,
 '57 kcal',
 nan,
 '449 kJ / 107 kcal',
 nan,
 '1024kj/241kcal',
 '38 kJ/ 9 Kcal',
 '399 kJ/94kcal',
 '2472 kJ/ 596 Kcal',
 nan,
 nan,
 '195 kJ / 46 kcal',
 '2161 kJ/ 518 kcal',
 '686 kJ/ 164 kcal',
 '1855 kJ/ 441 Kcal',
 nan,
 nan,
 '1394,2 kJ / 333 kcal',
 '2124 kJ/ 513 kcal ',
 nan,
 nan,
 nan,
 '543 kJ/ 131 Kcal',
 '476 kJ/ 115 Kcal',
 nan,
 '568 kJ/ 135 kcal',
 '377 kcal',
 '2174 kJ / 522 kcal',
 '267 kJ / 64 kcal',
 nan,
 '197 kJ / 47 kcal',
 'kJ 1058',
 '2338 kJ / 561 kcal',
 '349 kJ / 83 kcal',
 '430 kcal',
 nan,
 '1472 kJ/347 kcal',
 '2300 kJ/ 551 kcal',
 nan,
 '354 kcal',
 '176 kJ / 41 kcal',
 '260 kJ/ 62 kcal',
 '1426 kJ / 336 kcal',
 '156 kcal',
 ' 531 kcal',
 '348 kcal',
 nan,
 nan,
 nan,
 '1199 kJ / 284 kcal',
 '1015 kJ / 244 kcal',
 nan,
 '1578 kJ/373 kcal',
 '38 kcal',
 '34 kcal',
 '3688 kJ/ 897 Kcal',
 '1572 kJ/377 kcal',
 '671 kcal',
 '1847 kJ/443 kcal',
 '2406 kJ/580 kcal',
 '814 kJ/ 196 Kcal',
 '1821 kJ / 434 kcal',
 '869 kJ / 209 kcal',
 '262 kJ/62 kcal',
 nan,
 '669 kJ/159 kcal',
 nan,
 nan,
 nan,
 nan,
 '1403 kJ/330 kcal',
 nan,
 '1839 kJ / 439 kcal',
 '1303 kJ / 310 kcal ',
 '515 kJ / 124 kcal',
 '139 kJ/ 33 Kcal',
 '141 kcal',
 nan,
 '60 kcal',
 '313 kJ / 75 kcal',
 '242 kJ / 58 kcal',
 '1932 kJ/ 462 Kcal',
 nan,
 nan,
 '262 kJ/62 kcal',
 nan,
 nan,
 '1727 kJ / 409 kcal',
 '27 kcal',
 '27 kcal',
 nan,
 nan,
 nan,
 nan,
 nan,
 '1484 kJ/350 kcal',
 '441 kJ / 104 kcal',
 '2266 kJ/543 kcal',
 nan,
 '2166 kJ / 519 kcal',
 '482 kcal',
 nan,
 '595 kJ/ 143 Kcal',
 '839 kJ/ 202 kcal',
 nan,
 nan,
 '49 kJ/ 12 Kcal ',
 '1 kcal',
 nan,
 nan,
 '1184 kj / 283 kcal',
 '1444 kJ / 348 kcal',
 '570 kJ / 137 kcal',
 '478 kJ / 114 kcal',
 '3 kJ / 1 kcal',
 nan,
 '1469 kJ / 348 kcal',
 nan,
 nan,
 '406 kJ/97 kcal',
 nan,
 '345 kJ / 82 kcal',
 nan,
 '397 kJ/ 95 kcal',
 '37 kcal',
 '426 kJ / 101 kcal',
 '2672 kJ / 645 kcal',
 nan,
 '1489 kJ / 356 kcal',
 '21 kcal',
 '1559 kJ/ 368 Kcal',
 '601 kJ/144 kcal',
 '246 kJ/58 kcal',
 '838 kJ / 198 kcal',
 nan,
 '348,6 kJ / 83,7 kcal',
 '751 kJ / 180 kcal',
 '597 kJ/145 kcal',
 '406 kJ/97 kcal',
 '1173 kJ/282 kcal',
 '2193 kJ / 525 kcal',
 '112 kJ / 26 kcal',
 '391 kJ / 93 kcal',
 nan,
 nan,
 nan,
 '875 kJ/ 206 kcal',
 '1278',
 ' 1898 kJ / 451 kcal',
 nan,
 '414 kcal',
 nan,
 '397kcal',
 '106 kJ / 254 kcal',
 '1416 kJ / 333 kcal',
 '763 kJ / 184 kcal',
 '1395 kJ/ 332 kcal',
 '1723 kJ / 409 kcal',
 '35 kJ / 8 kcal',
 nan,
 nan,
 nan,
 '1588 kJ/374 kcal',
 nan,
 '574 kJ/137 kcal',
 '2043 kJ / 487 kcal',
 '281 kJ/66 kcal',
 '258 kJ/62 kcal',
 nan,
 '2043 kJ / 497 kcal',
 '787 kJ / 185 kcal',
 nan,
 '1824 kJ / 433 kcal',
 nan,
 '1564 kJ / 377 kcal',
 nan,
 '325 kJ/78 kcal',
 '1083 kJ / 256 kcal',
 '1353 kJ / 321 kcal',
 nan,
 nan,
 nan,
 nan,
 nan,
 '2490 kJ/ 602 Kcal',
 '904 kJ/',
 '145 kcal',
 nan,
 nan,
 '1968 kJ / 469 kcal',
 '243 kJ / 58 kcal',
 '154 kcal',
 '1823 kJ/ 438 Kcal',
 nan,
 nan,
 '1229 kJ/ 287 Kcal',
 '435 kJ/ 103 Kcal',
 nan,
 '227 kcal',
 '1653 kJ / 390 kcal',
 '3411 kJ / 830 kcal',
 nan,
 '338 kJ/80 kcal',
 nan,
 '697 kJ / 167 kcal',
 nan,
 '1038 kJ/247 kcal',
 '1453 kJ / 343 kcal',
 nan,
 '800 /191 (kJ/ kcal)',
 '492 kJ/ 117 Kcal',
 '888 kJ / 209 kcal',
 '297 kJ / 70 kcal',
 '904 kJ/216 kcal',
 nan,
 '815 kJ/196  kcal',
 '49 kcal',
 '1521 kJ',
 nan,
 '2091 kJ / 505 kcal',
 '1523kJ/364kcal',
 '2270 kJ/ 544 Kcal',
 '331 kJ / 78 kcal',
 '92 kJ / 22 kcal',
 nan,
 '1498 kJ/ 358 Kcal',
 '82 kJ / 19 kcal',
 '5 kJ / 1 kcal',
 '148 kcal',
 nan,
 '1714 kJ / 407 kcal',
 '2506 kJ/ 603 kcal',
 '373 kJ/ 89 Kcal',
 nan,
 '1600 kJ/ 380 kcal',
 '208\xa0kJ/50 kcal',
 '1007 kJ / 241 kcal',
 nan,
 '354 kJ / 84 kcal',
 '856 kJ / 201 kcal',
 '1086 kJ / 256 kcal',
 nan,
 '215 kJ/ 51 Kcal',
 nan,
 '1567 kJ/ 374 kcal',
 nan,
 '218 kJ / 51 kcal',
 nan,
 nan,
 '859 kJ / 207 kcal',
 nan,
 nan,
 nan,
 '7 kcal',
 nan,
 '559 kJ / 134 kcal',
 '372 kcal / 100 g',
 '2544 kJ / 616 kcal',
 nan,
 '1554 kJ / 373 kcal',
 nan,
 nan,
 '283 kJ/ 67 Kcal',
 nan,
 '1688 kJ / 403 kcal',
 '219 kJ/ 52 kcal',
 '152 kJ / 366 kcal',
 nan,
 '1500 kJ / 354 kcal',
 '1416 kJ / 333 kcal',
 '234/55',
 '400 kcal',
 '248 kJ / 59 kcal',
 '353 kcal/100 g',
 '211 kJ/50 kcal',
 '36 kJ / 8 kcal',
 '1000 kJ / 240 kcal',
 nan,
 nan,
 nan,
 '2516 kJ/ 608 Kcal',
 '2220 kJ/ 531 kcal',
 '1043 kJ/252 kcal',
 nan,
 '817 kJ / 192 kcal',
 nan,
 '3061 kJ / 744 kcal',
 '2355 kJ/568 kcal',
 '540 kcal',
 '617 kJ / 147 kcal',
 '308 kJ/75 kcal',
 nan,
 '2126 kJ/508 kcal',
 '1856 kJ / 440 kcal',
 '384 kJ / 93 kcal',
 nan,
 '1475 kJ/ 356 kcal',
 '1531 kJ / 361 kcal',
 '1390 kJ/327 kcal',
 nan,
 '253/60 kJ/kcal',
 '178/42 kJ/kcal',
 '923kJ / 220kcal',
 nan,
 ' 414 kJ/99 kcal',
 nan,
 '1834 kJ / 436 kcal',
 nan,
 nan,
 nan,
 nan,
 '253 kJ/60 kcal',
 '212 kJ / 50',
 '1821 kJ / 434 kcal',
 '71kJ / 17kcal',
 nan,
 nan,
 '265 kJ/63 kcal',
 nan,
 nan,
 '1733 kJ / 413 kcal',
 nan,
 '259kJ/61 Kcal',
 '2989 kJ/727 kcal',
 '342 kJ - 81 kcal',
 '1005 kJ/241 kcal',
 '1243 kJ',
 nan,
 nan,
 '709 kJ / 170 kcal (9 %)',
 '1197 kj / 282 kcal',
 '1797 kJ / 427 kcal',
 '385 kJ / 91 kcal',
 '1392 kJ/333 kcal',
 nan,
 '805 kJ/192 kcal',
 nan,
 '1823 kJ',
 '1665 kJ / 398 kcal',
 '1747 kJ',
 nan,
 '3110 KJ/ 755 KCAL',
 nan,
 '1469 kJ / 347 kcal',
 nan,
 nan,
 '3700kJ/900kcal',
 '189 kJ/ 45 Kcal',
 nan,
 nan,
 nan,
 '1141 kJ/274 kcal',
 '1380 kJ / 332 kcal',
 nan,
 nan,
 '895 kJ/217 kcal',
 nan,
 ...]

In [38]:
product_details['wartość energetyczna'] = (
    product_details['wartość energetyczna']
        .astype(str)
        .str.split('/')
        .str[-1]
        .str.replace(',', '.', regex=False)
        .str.lower()
        .str.strip()
)

In [39]:
mask = (
    product_details['wartość energetyczna'].str.contains("kj", case=False, na=False)
    & ~product_details['wartość energetyczna'].str.contains("kcal", case=False, na=False)
)


# extract kJ as float
kj = (
    product_details.loc[mask, 'wartość energetyczna']
        .str.extract(r'(\d*\.?\d+)')[0]
        .astype(float)
)

# convert to kcal
kcal = (kj / 4.184).round(2)

# write back (numeric kcal)
product_details.loc[mask, 'wartość energetyczna'] = kcal

In [40]:
product_details.isna().sum()

Referencja                                                              0
waga                                                                 6585
opis produktu                                                        4716
marka standaryzowana                                                 5678
jednostka opisowa                                                    5249
kraj pochodzenia                                                     5492
marka                                                                1593
wartość energetyczna                                                    0
tłuszcz                                                              4413
węglowodany                                                          4468
białko                                                               4295
sól                                                                  4610
przygotowanie                                                        9342
błonnik                                                              8039
pole rezerwowe 20                                                    9940
tym kwasy nasycone                                                   9544
witamina                                                             9678
rozszerzona nazwa produktu                                           9435
Unnamed: 43                                                          9895
cukry                                                                4511
referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal    9668
wapń                                                                 9984
włókno surowe                                                        9994
dtype: int64

In [41]:
mask = (
    product_details['wartość energetyczna'].isna()
    & product_details[['tłuszcz', 'węglowodany', 'białko']].notna().all(axis=1)
)

product_details.loc[mask, 'wartość energetyczna'] = (
    product_details.loc[mask, 'tłuszcz'] * 9
    + product_details.loc[mask, 'węglowodany'] * 4
    + product_details.loc[mask, 'białko'] * 4
)

In [42]:
product_details.head()

,Referencja,waga,opis produktu,marka standaryzowana,jednostka opisowa,kraj pochodzenia,marka,wartość energetyczna,tłuszcz,węglowodany,...,błonnik,pole rezerwowe 20,tym kwasy nasycone,witamina,rozszerzona nazwa produktu,Unnamed: 43,cukry,referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal,wapń,włókno surowe
0,97,20.0,Odpowiedni dla Wegetarian i Wegan.,Blue Dragon,g,Kraj pochodzenia - Korea (Republika Korei),Blue Dragon,348 kcal,0.0,41.0,...,NaN,NaN,NaN,NaN,NaN,NaN,6.2,NaN,NaN,NaN
1,143,512.0,Odpowiedni dla Wegetarian i Wegan.,Blue Dragon,g,Zapakowano w - Wielka Brytania,Blue Dragon,346 kcal,1.0,77.2,...,1.3,NaN,NaN,NaN,NaN,NaN,0.3,NaN,NaN,NaN
2,1864,80.0,Roślinne plastry,NaN,NaN,Rumunia,Verdino,240 kcal,20.4,7.1,...,3.1,NaN,NaN,NaN,NaN,NaN,6.4,NaN,NaN,NaN
3,7441,NaN,Blue Ocean. Kostka odświeżająca i czyszcząca ...,NaN,g,Wyprodukowano w Polsce,Kolorado,nan,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8499,NaN,NaN,NaN,g,Wyprodukowano w Polsce,Taverna Dell'Ancora,279 kcal,5.1,45.8,...,NaN,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN

In [43]:
def extract_kcal(x):
    if isinstance(x, (int, float)) and not pd.isna(x):
        return float(x)
    if isinstance(x, str):
        match = re.search(r'(\d*\.?\d+)\s*kcal', x.lower())
        if match:
            return float(match.group(1))
        return np.nan

    return np.nan


product_details['wartość energetyczna'] = (
    product_details['wartość energetyczna']
        .apply(extract_kcal)
)

In [44]:
product_details['wartość energetyczna'].to_list()[:20]

[348.0,
 346.0,
 240.0,
 nan,
 279.0,
 nan,
 nan,
 nan,
 1.0,
 nan,
 nan,
 690.0,
 nan,
 63.0,
 37.0,
 nan,
 nan,
 230.0,
 580.0,
 637.0]

In [45]:
product_base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10261 entries, 0 to 10260
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Referencja       10261 non-null  object
 1   EAN              10261 non-null  object
 2   Nazwa            10261 non-null  object
 3   Dane Produktowe  10261 non-null  object
dtypes: object(4)
memory usage: 320.8+ KB

In [46]:
product_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10261 entries, 0 to 10260
Data columns (total 23 columns):
 #   Column                                                             Non-Null Count  Dtype
---  ------                                                             --------------  -----
 0   Referencja                                                         10261 non-null  object
 1   waga                                                               3676 non-null   float64
 2   opis produktu                                                      5545 non-null   object
 3   marka standaryzowana                                               4583 non-null   object
 4   jednostka opisowa                                                  5012 non-null   object
 5   kraj pochodzenia                                                   4769 non-null   object
 6   marka                                                              8668 non-null   object
 7   wartość energetyczna                                               5444 non-null   float64
 8   tłuszcz                                                            5848 non-null   float64
 9   węglowodany                                                        5793 non-null   float64
 10  białko                                                             5966 non-null   float64
 11  sól                                                                5651 non-null   float64
 12  przygotowanie                                                      919 non-null    object
 13  błonnik                                                            2222 non-null   float64
 14  pole rezerwowe 20                                                  321 non-null    object
 15  tym kwasy nasycone                                                 717 non-null    object
 16  witamina                                                           583 non-null    object
 17  rozszerzona nazwa produktu                                         826 non-null    object
 18  Unnamed: 43                                                        366 non-null    object
 19  cukry                                                              5750 non-null   float64
 20  referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal  593 non-null    object
 21  wapń                                                               277 non-null    object
 22  włókno surowe                                                      267 non-null    object
dtypes: float64(8), object(15)
memory usage: 1.8+ MB

In [47]:
product_details[product_details['Referencja'] == '43444']

,Referencja,waga,opis produktu,marka standaryzowana,jednostka opisowa,kraj pochodzenia,marka,wartość energetyczna,tłuszcz,węglowodany,...,błonnik,pole rezerwowe 20,tym kwasy nasycone,witamina,rozszerzona nazwa produktu,Unnamed: 43,cukry,referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal,wapń,włókno surowe
1257,43444,NaN,Cebula bogata jest w substancje bakteriobójcz...,NaN,NaN,NaN,Cebula,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
product_details['kategoria'] = np.where(product_details['wartość energetyczna'].notna() | product_base['Nazwa'].str.contains(r'warzywa auchan|owoce auchan|cukiernia auchan|piekarnia auchan|na wagę', case=False, na=False), 'Food', 'Not food')

In [49]:
product_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10261 entries, 0 to 10260
Data columns (total 24 columns):
 #   Column                                                             Non-Null Count  Dtype
---  ------                                                             --------------  -----
 0   Referencja                                                         10261 non-null  object
 1   waga                                                               3676 non-null   float64
 2   opis produktu                                                      5545 non-null   object
 3   marka standaryzowana                                               4583 non-null   object
 4   jednostka opisowa                                                  5012 non-null   object
 5   kraj pochodzenia                                                   4769 non-null   object
 6   marka                                                              8668 non-null   object
 7   wartość energetyczna                                               5444 non-null   float64
 8   tłuszcz                                                            5848 non-null   float64
 9   węglowodany                                                        5793 non-null   float64
 10  białko                                                             5966 non-null   float64
 11  sól                                                                5651 non-null   float64
 12  przygotowanie                                                      919 non-null    object
 13  błonnik                                                            2222 non-null   float64
 14  pole rezerwowe 20                                                  321 non-null    object
 15  tym kwasy nasycone                                                 717 non-null    object
 16  witamina                                                           583 non-null    object
 17  rozszerzona nazwa produktu                                         826 non-null    object
 18  Unnamed: 43                                                        366 non-null    object
 19  cukry                                                              5750 non-null   float64
 20  referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal  593 non-null    object
 21  wapń                                                               277 non-null    object
 22  włókno surowe                                                      267 non-null    object
 23  kategoria                                                          10261 non-null  object
dtypes: float64(8), object(16)
memory usage: 1.9+ MB

In [50]:
product_details.head()

,Referencja,waga,opis produktu,marka standaryzowana,jednostka opisowa,kraj pochodzenia,marka,wartość energetyczna,tłuszcz,węglowodany,...,pole rezerwowe 20,tym kwasy nasycone,witamina,rozszerzona nazwa produktu,Unnamed: 43,cukry,referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal,wapń,włókno surowe,kategoria
0,97,20.0,Odpowiedni dla Wegetarian i Wegan.,Blue Dragon,g,Kraj pochodzenia - Korea (Republika Korei),Blue Dragon,348.0,0.0,41.0,...,NaN,NaN,NaN,NaN,NaN,6.2,NaN,NaN,NaN,Food
1,143,512.0,Odpowiedni dla Wegetarian i Wegan.,Blue Dragon,g,Zapakowano w - Wielka Brytania,Blue Dragon,346.0,1.0,77.2,...,NaN,NaN,NaN,NaN,NaN,0.3,NaN,NaN,NaN,Food
2,1864,80.0,Roślinne plastry,NaN,NaN,Rumunia,Verdino,240.0,20.4,7.1,...,NaN,NaN,NaN,NaN,NaN,6.4,NaN,NaN,NaN,Food
3,7441,NaN,Blue Ocean. Kostka odświeżająca i czyszcząca ...,NaN,g,Wyprodukowano w Polsce,Kolorado,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not food
4,8499,NaN,NaN,NaN,g,Wyprodukowano w Polsce,Taverna Dell'Ancora,279.0,5.1,45.8,...,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,Food

In [51]:
product_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10261 entries, 0 to 10260
Data columns (total 24 columns):
 #   Column                                                             Non-Null Count  Dtype
---  ------                                                             --------------  -----
 0   Referencja                                                         10261 non-null  object
 1   waga                                                               3676 non-null   float64
 2   opis produktu                                                      5545 non-null   object
 3   marka standaryzowana                                               4583 non-null   object
 4   jednostka opisowa                                                  5012 non-null   object
 5   kraj pochodzenia                                                   4769 non-null   object
 6   marka                                                              8668 non-null   object
 7   wartość energetyczna                                               5444 non-null   float64
 8   tłuszcz                                                            5848 non-null   float64
 9   węglowodany                                                        5793 non-null   float64
 10  białko                                                             5966 non-null   float64
 11  sól                                                                5651 non-null   float64
 12  przygotowanie                                                      919 non-null    object
 13  błonnik                                                            2222 non-null   float64
 14  pole rezerwowe 20                                                  321 non-null    object
 15  tym kwasy nasycone                                                 717 non-null    object
 16  witamina                                                           583 non-null    object
 17  rozszerzona nazwa produktu                                         826 non-null    object
 18  Unnamed: 43                                                        366 non-null    object
 19  cukry                                                              5750 non-null   float64
 20  referencyjna wartość spożycia dla przeciętnej osoby dorosłej kcal  593 non-null    object
 21  wapń                                                               277 non-null    object
 22  włókno surowe                                                      267 non-null    object
 23  kategoria                                                          10261 non-null  object
dtypes: float64(8), object(16)
memory usage: 1.9+ MB

In [52]:
from unidecode import unidecode

product_base['Nazwa'] = product_base['Nazwa'].apply(lambda x: unidecode(x))

In [53]:
product_details = product_details.fillna("")

In [54]:
product_details.to_csv('product_details_cleaned.csv')
product_base.to_csv('product_base_cleaned.csv')